package dev.phantom.ac;

import org.junit.jupiter.api.Test; import java.util.*; import static org.junit.jupiter.api.Assertions.*; import static dev.phantom.ac.Maths.*; import static dev.phantom.ac.Packets.*; import static dev.phantom.ac.Simulation.*; import static dev.phantom.ac.Validation.*;
class CoreTest {
  private static World.Snapshot ground(){Map<World.Pos,World.Block>b=new HashMap<>();for(int x=-3;x<=3;x++)for(int z=-3;z<=3;z++)b.put(new World.Pos(x,-1,z),World.Block.FULL);return new World.Snapshot(b);}
  @Test void normalizerOrdersAndMarksDuplicateAndOutOfOrder(){var n=new Normalizer().normalize(List.of(new RawPacket(2,20,new Velocity(Vec3.ZERO)),new RawPacket(1,10,new Velocity(Vec3.ZERO)),new RawPacket(1,30,new Velocity(Vec3.ZERO))));assertEquals(List.of(1L,2L,1L),n.stream().map(NormalizedPacket::sequence).toList());assertTrue(n.get(2).flags().contains(PacketFlag.DUPLICATE));assertTrue(n.get(2).flags().contains(PacketFlag.OUT_OF_ORDER));}
  @Test void timelineKeepsMultiplePacketsPerTick(){var t=Timeline.assign(new Normalizer().normalize(List.of(new RawPacket(1,1,new Velocity(Vec3.ZERO)),new RawPacket(2,49_999_999,new Velocity(Vec3.ZERO)))),0,50_000_000);assertEquals(2,t.events().size());assertEquals(0,t.events().get(1).serverTick());}
  @Test void inputProjectionPersistsChangedInputAndMarksEarlierMovementUnknown(){var t=Timeline.assign(new Normalizer().normalize(List.of(new RawPacket(1,1,new Move(Vec3.ZERO,0f,0f,true,null)),new RawPacket(2,2,new ClientInput(true,false,false,true,false,false,false)),new RawPacket(3,3,new Move(Vec3.ZERO,0f,0f,true,null)))),0,50_000_000);var samples=Timeline.projectInputs(t);assertTrue(samples.getFirst().input().isEmpty());assertEquals(new Input(1,1,false),samples.get(1).input().orElseThrow());}
  @Test void replayRoundTripAndDeterminism(){var t=Timeline.assign(new Normalizer().normalize(List.of(new RawPacket(1,0,new Velocity(new Vec3(1,2,3))),new RawPacket(2,1,new Gamemode("creative")))),0,50_000_000);var bytes=new Timeline.Codec().encode(t);var decoded=new Timeline.Codec().decode(bytes);assertEquals(t,decoded);assertEquals(Replay.reconstruct(State.Player.initial(Vec3.ZERO),t),Replay.reconstruct(State.Player.initial(Vec3.ZERO),decoded));}
  @Test void malformedReplayFails(){assertThrows(IllegalArgumentException.class,()->new Timeline.Codec().decode(new byte[]{1,2,3}));}
  @Test void stateDoesNotInventMissingInformation(){var s=State.Player.initial(Vec3.ZERO);var out=State.apply(s,new NormalizedPacket(1,1,new Move(new Vec3(1,2,3),5f,6f,false,null),EnumSet.of(PacketFlag.DUPLICATE)));assertTrue(out.uncertain());assertEquals(new Vec3(1,2,3),out.position());}
  @Test void absentGroundBitPropagatesUncertaintyInsteadOfGuessing(){var out=State.apply(State.Player.initial(Vec3.ZERO),new NormalizedPacket(1,1,new Move(new Vec3(1,2,3),0f,0f,null,null),EnumSet.of(PacketFlag.NORMAL)));assertTrue(out.uncertain());assertTrue(out.onGround());}
  @Test void matchingTeleportAcknowledgementClearsSynchronizationBarrier(){var s=State.apply(State.Player.initial(Vec3.ZERO),new NormalizedPacket(1,0,new Teleport(7,new Vec3(1,2,3),0,0),EnumSet.of(PacketFlag.NORMAL)));var confirmed=State.apply(s,new NormalizedPacket(2,1,new TeleportConfirm(7),EnumSet.of(PacketFlag.NORMAL)));assertTrue(confirmed.awaitingTeleport().isEmpty());assertFalse(confirmed.uncertain());}
  @Test void wrongTeleportAcknowledgementIsExplicitlyUncertain(){var s=State.apply(State.Player.initial(Vec3.ZERO),new NormalizedPacket(1,0,new Teleport(7,Vec3.ZERO,0,0),EnumSet.of(PacketFlag.NORMAL)));assertTrue(State.apply(s,new NormalizedPacket(2,1,new TeleportConfirm(8),EnumSet.of(PacketFlag.NORMAL))).uncertain());}
  @Test void relativeTeleportUsesPriorReconstructedPositionAndRotation(){var start=new State.Player(new Vec3(10,64,-2),Vec3.ZERO,90,10,true,"survival",Map.of(),OptionalInt.empty(),false);var t=new Teleport(7,new Vec3(1,2,3),5,6,true,true,true,true,true);var result=State.apply(start,new NormalizedPacket(1,0,t,EnumSet.of(PacketFlag.NORMAL)));assertEquals(new Vec3(11,66,1),result.position());assertEquals(95,result.yaw());assertEquals(16,result.pitch());assertEquals(7,result.awaitingTeleport().getAsInt());}
  @Test void collisionFlatGroundWallAndSlab(){var b=new HashMap<World.Pos,World.Block>();b.put(new World.Pos(0,-1,0),World.Block.FULL);b.put(new World.Pos(1,0,0),World.Block.FULL);b.put(new World.Pos(0,0,1),World.Block.SLAB_BOTTOM);var w=new World.Snapshot(b);assertEquals(0,World.collide(w,Aabb.playerAt(new Vec3(.5,0,.5)),new Vec3(0,-1,0)).y());assertTrue(World.collide(w,Aabb.playerAt(new Vec3(.5,0,.5)),new Vec3(1,0,0)).x()<1);assertTrue(w.collisions(new Aabb(0,0,1,1,.5,2)).size()>0);}
  @Test void noCollisionInNarrowAir(){assertEquals(new Vec3(.2,.1,-.3),World.collide(new World.Snapshot(Map.of()),Aabb.playerAt(Vec3.ZERO),new Vec3(.2,.1,-.3)));}
  @Test void collisionShapesCoverPartialBlocksAndAllStairOrientations(){for(World.Block block:List.of(World.Block.CARPET,World.Block.SNOW_LAYER_1,World.Block.FENCE,World.Block.STAIRS_NORTH,World.Block.STAIRS_SOUTH,World.Block.STAIRS_EAST,World.Block.STAIRS_WEST)){assertFalse(World.BlockShapes.shapes(block,0,0,0).isEmpty(),()->"missing shape for "+block);}assertEquals(.0625,World.BlockShapes.shapes(World.Block.CARPET,0,0,0).getFirst().maxY());assertEquals(.125,World.BlockShapes.shapes(World.Block.SNOW_LAYER_1,0,0,0).getFirst().maxY());}
  @Test void snowLayerCollisionHeightsAreExactEighths(){for(int layer=1;layer<=8;layer++){World.Block block=World.Block.values()[World.Block.SNOW_LAYER_1.ordinal()+layer-1];assertEquals(layer/8.0,World.BlockShapes.shapes(block,0,0,0).getFirst().maxY(),0.0,"layer "+layer);}}
  @Test void stepResolverOnlyUsesAPathWhenItImprovesHorizontalProgress(){var world=new World.Snapshot(Map.of(new World.Pos(1,0,0),World.Block.SLAB_BOTTOM));var direct=World.resolve(world,Aabb.playerAt(new Vec3(.5,0,.5)),new Vec3(1,0,0),false);var stepped=World.resolveWithStep(world,Aabb.playerAt(new Vec3(.5,0,.5)),new Vec3(1,0,0),.6);assertTrue(stepped.resolved().x()>=direct.resolved().x());assertTrue(stepped.stepped());}
  @Test void negativeStepHeightIsRejected(){assertThrows(IllegalArgumentException.class,()->World.resolveWithStep(new World.Snapshot(Map.of()),Aabb.playerAt(Vec3.ZERO),Vec3.ZERO,-.1));}
  @Test void worldHistoryAppliesChangesOnlyWhenVisibleToClient(){var p=new World.Pos(0,0,0);var history=new World.History(World.Snapshot.emptyVisibleChunks(List.of(new World.Chunk(0,0))),List.of(new World.Change(4,p,World.Block.FULL),new World.Change(8,p,World.Block.AIR)));assertEquals(World.Block.AIR,history.at(3).blockAt(0,0,0));assertEquals(World.Block.FULL,history.at(4).blockAt(0,0,0));assertEquals(World.Block.AIR,history.at(8).blockAt(0,0,0));}
  @Test void simulationIsDeterministicAndJumps(){var p=State.Player.initial(new Vec3(0,0,0));var physics=new Vanilla12111Physics();var a=physics.tick(p,new Input(1,0,true),ground());var b=physics.tick(p,new Input(1,0,true),ground());assertEquals(a,b);assertTrue(a.position().y()>0);}
  @Test void gravityAndWallTransition(){var physics=new Vanilla12111Physics();var p=new State.Player(new Vec3(0,5,0),Vec3.ZERO,0,0,false,"survival",Map.of(),OptionalInt.empty(),false);assertTrue(physics.tick(p,new Input(0,0,false),ground()).velocity().y()<0);}
  @Test void unsupportedFluidIsUncertain(){var w=new World.Snapshot(Map.of(new World.Pos(0,0,0),World.Block.WATER));assertTrue(new Vanilla12111Physics().tick(State.Player.initial(Vec3.ZERO),new Input(0,0,false),w).uncertain());}
  @Test void traceReportsFirstDivergence(){var p=State.Player.initial(Vec3.ZERO);var a=new Trace(List.of(new Frame(0,p,new Input(0,0,false),false),new Frame(1,p,new Input(0,0,false),false)));var q=new State.Player(new Vec3(1,0,0),Vec3.ZERO,0,0,true,"survival",Map.of(),OptionalInt.empty(),false);var b=new Trace(List.of(new Frame(0,p,new Input(0,0,false),false),new Frame(1,q,new Input(0,0,false),false)));assertEquals(1,firstDivergence(a,b,0).orElseThrow().firstDivergentTick());}
  @Test void traceExchangeRoundTripsIndependentObservations(){var p=State.Player.initial(Vec3.ZERO);var trace=new Trace(List.of(new Frame(1,p,new Input(1,0,false),false)));assertEquals(trace,TraceExchange.read(TraceExchange.write(trace)));}
  @Test void traceExchangeRejectsMissingHeaderAndNonMonotonicTicks(){assertThrows(IllegalArgumentException.class,()->TraceExchange.read(List.of("bad")));assertThrows(IllegalArgumentException.class,()->TraceExchange.read(List.of(TraceExchange.HEADER,"1,0,0,0,0,0,0,true,0,0,false,false","1,0,0,0,0,0,0,true,0,0,false,false")));}
  @Test void reachabilityNeverRejectsOwnCandidate(){var r=new ReachableStates(new Vanilla12111Physics()).next(State.Player.initial(Vec3.ZERO),ground(),false);assertEquals(Verdict.POSSIBLE,r.verdict());var candidate=r.candidates().iterator().next();assertEquals(Verdict.POSSIBLE,Validation.validate(candidate,r).verdict());}
  @Test void observedInputConstrainsReachabilityWithoutArbitraryTolerance(){var state=State.Player.initial(Vec3.ZERO);var r=new ReachableStates(new Vanilla12111Physics()).next(state,ground(),false,new ClientInput(true,false,false,false,false,false,false));assertEquals(1,r.candidates().size());assertEquals(Verdict.UNCERTAIN,new ReachableStates(new Vanilla12111Physics()).next(state,ground(),false,new ClientInput(true,false,false,false,false,false,true)).verdict());}
  @Test void multiTickSearchMatchesKnownInputSequence(){var physics=new Vanilla12111Physics();var start=State.Player.initial(Vec3.ZERO);var inputs=List.<Optional<Input>>of(Optional.of(new Input(1,0,false)),Optional.of(new Input(1,0,true)));var result=new ReachableStates(physics).advance(start,10,inputs,ignored->ground(),16);var expected=physics.tick(physics.tick(start,new Input(1,0,false),ground()),new Input(1,0,true),ground());assertEquals(Verdict.POSSIBLE,result.verdict());assertEquals(2,result.simulatedTicks());assertEquals(Set.of(expected),result.candidates());}
  @Test void multiTickSearchReportsUncertaintyInsteadOfPruningBranches(){var result=new ReachableStates(new Vanilla12111Physics()).advance(State.Player.initial(Vec3.ZERO),0,List.of(Optional.empty()),ignored->ground(),1);assertEquals(Verdict.UNCERTAIN,result.verdict());assertTrue(result.reasons().getFirst().contains("budget exceeded"));}
  @Test void multiTickSearchRejectsInvalidBudget(){assertThrows(IllegalArgumentException.class,()->new ReachableStates(new Vanilla12111Physics()).advance(State.Player.initial(Vec3.ZERO),0,List.of(),ignored->ground(),0));}
  @Test void uncertaintyNeverBecomesViolation(){var r=new ReachableStates(new Vanilla12111Physics()).next(State.Player.initial(Vec3.ZERO),ground(),true);assertEquals(Verdict.UNCERTAIN,Validation.validate(State.Player.initial(Vec3.ZERO),r).verdict());}
  @Test void impossibleEvidenceExplainsWhy(){var r=new ReachableStates(new Vanilla12111Physics()).next(State.Player.initial(Vec3.ZERO),ground(),false);var observed=new State.Player(new Vec3(100,0,0),Vec3.ZERO,0,0,true,"survival",Map.of(),OptionalInt.empty(),false);var e=Validation.validate(observed,r);assertEquals(Verdict.IMPOSSIBLE,e.verdict());assertTrue(e.nearestHorizontalDistance()>90);}
  @Test void observedVelocityMustAlsoBeReachable(){var r=new ReachableStates(new Vanilla12111Physics()).next(State.Player.initial(Vec3.ZERO),ground(),false);var candidate=r.candidates().iterator().next();var altered=new State.Player(candidate.position(),new Vec3(999,999,999),candidate.yaw(),candidate.pitch(),candidate.onGround(),candidate.gamemode(),candidate.effects(),candidate.awaitingTeleport(),false);assertEquals(Verdict.IMPOSSIBLE,Validation.validate(altered,r).verdict());}
  @Test void synchronizationUsesTimingAsUncertaintyNotCheat(){var s=Validation.synchronize(10,100_000_000,30_000_000,false);assertTrue(s.uncertain());assertTrue(s.latestClientTick()>10);}
  @Test void diagnosticsExposeTimelineAndSynchronizationEvidenceWithoutCheatVerdict(){var packets=new Normalizer().normalize(List.of(new RawPacket(2,2,new Move(Vec3.ZERO,0f,0f,true,null)),new RawPacket(1,1,new TeleportConfirm(4)),new RawPacket(1,3,new Move(Vec3.ZERO,0f,0f,true,null))));var report=Diagnostics.audit(Timeline.assign(packets,0,50_000_000));assertEquals(2,report.movementPackets());assertEquals(1,report.teleportConfirms());assertTrue(report.alerts().stream().anyMatch(a->a.category()==Diagnostics.Category.TIMELINE));assertTrue(report.alerts().stream().anyMatch(a->a.category()==Diagnostics.Category.SYNCHRONIZATION));assertTrue(report.alerts().stream().noneMatch(a->a.message().toLowerCase().contains("cheat")));}
  @Test void matchingTeleportAndInputCoverageProduceNoDiagnosticAlert(){var packets=new Normalizer().normalize(List.of(new RawPacket(1,1,new Teleport(4,Vec3.ZERO,0,0)),new RawPacket(2,2,new TeleportConfirm(4)),new RawPacket(3,3,new ClientInput(true,false,false,false,false,false,false)),new RawPacket(4,4,new Move(Vec3.ZERO,0f,0f,true,null))));assertTrue(Diagnostics.audit(Timeline.assign(packets,0,50_000_000)).alerts().isEmpty());}
  @Test void invisibleChunksNeverBecomeImplicitAir(){var world=World.Snapshot.emptyVisibleChunks(List.of());assertEquals(World.Block.UNKNOWN,world.blockAt(0,0,0));assertTrue(world.hasUnsupported(Aabb.playerAt(Vec3.ZERO)));assertTrue(new Vanilla12111Physics().tick(State.Player.initial(Vec3.ZERO),new Input(0,0,false),world).uncertain());}
  @Test void visibilityHistoryAppliesChunkAndBlockPacketsAtTheirClientTicks(){var history=new World.VisibilityHistory();var chunk=new World.Chunk(0,0);var position=new World.Pos(1,64,1);history.chunkVisible(10,chunk);history.blockChanged(11,position,World.Block.FULL);history.blockChanged(12,position,World.Block.AIR);history.chunkUnloaded(13,chunk);assertEquals(World.Block.UNKNOWN,history.at(9).blockAt(1,64,1));assertEquals(World.Block.AIR,history.at(10).blockAt(1,64,1));assertEquals(World.Block.FULL,history.at(11).blockAt(1,64,1));assertEquals(World.Block.AIR,history.at(12).blockAt(1,64,1));assertEquals(World.Block.UNKNOWN,history.at(13).blockAt(1,64,1));}
  @Test void invisibleChunkUpdatesDoNotInventFutureWorldState(){var history=new World.VisibilityHistory();var position=new World.Pos(1,64,1);history.blockChanged(2,position,World.Block.FULL);history.chunkVisible(3,new World.Chunk(0,0));assertEquals(World.Block.AIR,history.at(3).blockAt(1,64,1));}
  @Test void timelineWorldPacketsReconstructTheClientVisibleWorld(){var chunk=new World.Chunk(0,0);var position=new World.Pos(1,64,1);var raw=List.of(new RawPacket(1,0,new ChunkData(chunk,Map.of(position,World.Block.FULL))),new RawPacket(2,50_000_000,new BlockChange(position,World.Block.AIR)),new RawPacket(3,100_000_000,new ChunkUnload(chunk)));var history=World.fromTimeline(Timeline.assign(new Normalizer().normalize(raw),0,50_000_000));assertEquals(World.Block.FULL,history.at(0).blockAt(1,64,1));assertEquals(World.Block.AIR,history.at(1).blockAt(1,64,1));assertEquals(World.Block.UNKNOWN,history.at(2).blockAt(1,64,1));}
  @Test void liveComparisonAnchorsFirstObservationInsteadOfTreatingItAsEvidence(){var timeline=Timeline.assign(new Normalizer().normalize(List.of(new RawPacket(1,0,new Move(Vec3.ZERO,0f,0f,true,null)))),0,50_000_000);var report=LiveValidation.analyze(timeline,64);assertEquals(1,report.movementObservations());assertEquals(Verdict.UNCERTAIN,report.findings().getFirst().verdict());}
  @Test void reachableSearchReportsDeterministicBudgetMetrics(){var result=new ReachableStates(new Vanilla12111Physics()).advance(State.Player.initial(Vec3.ZERO),0,List.of(Optional.empty()),ignored->ground(),1);assertEquals(Verdict.UNCERTAIN,result.verdict());assertEquals(18,result.peakCandidates());assertEquals(17,result.prunedCandidates());assertTrue(result.candidates().isEmpty());}
  @Test void synchronizationRejectsNegativeMeasurements(){assertThrows(IllegalArgumentException.class,()->Validation.synchronize(-1,0,0,false));assertThrows(IllegalArgumentException.class,()->Validation.synchronize(1,-1,0,false));assertThrows(IllegalArgumentException.class,()->Validation.synchronize(1,0,-1,false));}
}
