package dev.phantom.ac;

import java.util.*;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import static dev.phantom.ac.Maths.Vec3;
import static dev.phantom.ac.Packets.*;
import static dev.phantom.ac.Phase7Timing.*;

class Phase7TimingTest {
  private static Timeline.Snapshot timeline(RawPacket... packets){return Timeline.assign(new Normalizer().normalize(List.of(packets)),0,50_000_000L);}
  private static Config exactConfig(){return new Config(50_000_000L,50_000_000L,50_000_000L,new LatencyBounds(0,0),new LatencyBounds(0,0),new TickDelayBounds(0,0),new TickDelayBounds(0,0),250_000_000L,3,128);}
  @Test void serverTickAssociationIsDeterministicAndBurstPreserving(){var t=timeline(new RawPacket(1,10_000_000L,new Move(Vec3.ZERO,0f,0f,true,0L)),new RawPacket(2,20_000_000L,new Move(new Vec3(.1,0,0),0f,0f,true,1L)),new RawPacket(3,49_999_999L,new Move(new Vec3(.2,0,0),0f,0f,true,2L)));var a=Phase7Timing.reconstruct(t,exactConfig());var b=Phase7Timing.reconstruct(t,exactConfig());assertEquals(a.canonicalText(),b.canonicalText());assertEquals(3,a.frames().size());assertEquals(List.of(0L,0L,0L),a.frames().stream().map(f->f.timing().serverTick()).toList());}
  @Test void explicitClientTickIsHonoredAsHardTimingFact(){var r=Phase7Timing.reconstruct(timeline(new RawPacket(1,0,new Move(Vec3.ZERO,0f,0f,true,42L))),exactConfig());var timing=r.frames().getFirst().timing();assertEquals(Range.exact(42),timing.packetGenerationClientTicks());assertEquals(TimingSource.EXPLICIT_CLIENT_TICK,timing.source());assertFalse(timing.uncertain());}
  @Test void relativeClientTicksBoundMultipleClientTicksBetweenServerObservations(){var r=Phase7Timing.reconstruct(timeline(new RawPacket(1,0,new Move(Vec3.ZERO,0f,0f,true,0L)),new RawPacket(2,200_000_000L,new Move(new Vec3(.1,0,0),0f,0f,true,null))),exactConfig());assertEquals(Range.exact(0),r.frames().get(0).timing().packetGenerationClientTicks());assertEquals(Range.exact(4),r.frames().get(1).timing().packetGenerationClientTicks());}
  @Test void idleObservationGapDoesNotMeanClientDidNothing(){var r=Phase7Timing.reconstruct(timeline(new RawPacket(1,0,new Move(Vec3.ZERO,0f,0f,true,0L)),new RawPacket(2,300_000_000L,new Move(new Vec3(.2,0,0),0f,0f,true,6L))),exactConfig());assertEquals(SyncStatus.RECOVERING,r.finalState().status());assertTrue(r.frames().get(1).timing().windows().stream().anyMatch(w->w.kind()==WindowKind.PACKET_GAP));}
  @Test void asymmetricLatencyIsRepresentedPerDirection(){Config c=new Config(50_000_000L,50_000_000L,50_000_000L,new LatencyBounds(40_000_000L,60_000_000L),new LatencyBounds(10_000_000L,20_000_000L),new TickDelayBounds(0,0),new TickDelayBounds(0,0),250_000_000L,3,128);var r=Phase7Timing.reconstruct(timeline(new RawPacket(1,100_000_000L,new Move(Vec3.ZERO,0f,0f,true,0L)),new RawPacket(2,100_000_000L,new Velocity(Vec3.ZERO))),c);assertEquals(new TimeRange(40_000_000L,60_000_000L),r.frames().get(0).timing().packetGenerationNanos());assertEquals(new TimeRange(110_000_000L,120_000_000L),r.frames().get(1).timing().clientProcessingNanos());}
  @Test void jitterWidensClientTickRangeInsteadOfSelectingOneTick(){Config c=new Config(50_000_000L,50_000_000L,50_000_000L,new LatencyBounds(0,30_000_000L),new LatencyBounds(0,30_000_000L),new TickDelayBounds(0,0),new TickDelayBounds(0,0),250_000_000L,3,128);var r=Phase7Timing.reconstruct(timeline(new RawPacket(1,0,new Move(Vec3.ZERO,0f,0f,true,0L)),new RawPacket(2,100_000_000L,new Move(new Vec3(.1,0,0),0f,0f,true,null))),c);assertTrue(r.frames().get(1).timing().packetGenerationClientTicks().width()>=1);assertTrue(r.frames().get(1).timing().uncertain());}
  @Test void inputAndMovementHaveDifferentCausalTimingFields(){Config c=new Config(50_000_000L,50_000_000L,50_000_000L,new LatencyBounds(0,0),new LatencyBounds(0,0),new TickDelayBounds(1,1),new TickDelayBounds(1,1),250_000_000L,3,128);var r=Phase7Timing.reconstruct(timeline(new RawPacket(1,0,new Move(Vec3.ZERO,0f,0f,true,0L)),new RawPacket(2,50_000_000L,new ClientInput(true,false,false,false,false,false,false)),new RawPacket(3,100_000_000L,new Move(new Vec3(.2,0,0),0f,0f,true,2L))),c);EventTiming input=r.timingFor(2).orElseThrow();EventTiming movement=r.timingFor(3).orElseThrow();assertEquals(Range.exact(1),input.inputClientTicks());assertEquals(Range.exact(2),input.simulationClientTicks());assertEquals(Range.exact(2),movement.packetGenerationClientTicks());assertEquals(Range.exact(1),movement.simulationClientTicks());}
  @Test void velocityCreatesExplicitSynchronizationWindow(){var r=Phase7Timing.reconstruct(timeline(new RawPacket(1,0,new Move(Vec3.ZERO,0f,0f,true,0L)),new RawPacket(2,50_000_000L,new Velocity(new Vec3(.4,.2,0)))),exactConfig());assertTrue(r.frames().get(1).timing().windows().stream().anyMatch(w->w.kind()==WindowKind.VELOCITY));assertTrue(r.frames().get(1).timing().windows().stream().anyMatch(w->w.reason().contains("movement")));}
  @Test void teleportStartsRecoveryAndMatchingAckDoesNotInstantlyReassertSynchronization(){var r=Phase7Timing.reconstruct(timeline(new RawPacket(1,0,new Move(Vec3.ZERO,0f,0f,true,0L)),new RawPacket(2,50_000_000L,new Teleport(7,Vec3.ZERO,0f,0f)),new RawPacket(3,100_000_000L,new TeleportConfirm(7)),new RawPacket(4,150_000_000L,new Move(new Vec3(.1,0,0),0f,0f,true,3L)),new RawPacket(5,200_000_000L,new Move(new Vec3(.2,0,0),0f,0f,true,4L)),new RawPacket(6,250_000_000L,new Move(new Vec3(.3,0,0),0f,0f,true,5L))),exactConfig());assertEquals(SyncStatus.RECOVERING,r.frames().get(1).after().status());assertEquals(SyncStatus.RECOVERING,r.frames().get(2).after().status());assertEquals(SyncStatus.SYNCHRONIZED,r.finalState().status());assertTrue(r.finalState().pendingTeleportId().isEmpty());}
  @Test void wrongTeleportAckLeavesAmbiguousSynchronization(){var r=Phase7Timing.reconstruct(timeline(new RawPacket(1,0,new Move(Vec3.ZERO,0f,0f,true,0L)),new RawPacket(2,50_000_000L,new Teleport(7,Vec3.ZERO,0f,0f)),new RawPacket(3,100_000_000L,new TeleportConfirm(8))),exactConfig());assertEquals(SyncStatus.AMBIGUOUS,r.finalState().status());assertTrue(r.frames().get(2).timing().reasons().stream().anyMatch(s->s.contains("did not match")||s.contains("acknowledgement")));}
  @Test void captureSequenceGapIsRetainedAsUncertainty(){var t=timeline(new RawPacket(1,0,new Move(Vec3.ZERO,0f,0f,true,0L)),new RawPacket(3,50_000_000L,new Move(new Vec3(.1,0,0),0f,0f,true,1L)));var r=Phase7Timing.reconstruct(t,exactConfig());assertTrue(r.frames().get(1).timing().reasons().stream().anyMatch(s->s.contains("sequence gap")));assertTrue(r.frames().get(1).timing().uncertain());}
  @Test void reorderingRemainsArrivalEvidenceAndDoesNotSilentlyResortBySequence(){var t=timeline(new RawPacket(1,0,new Move(Vec3.ZERO,0f,0f,true,0L)),new RawPacket(3,50_000_000L,new Move(new Vec3(.3,0,0),0f,0f,true,3L)),new RawPacket(2,60_000_000L,new Move(new Vec3(.2,0,0),0f,0f,true,2L)));assertEquals(List.of(1L,3L,2L),t.events().stream().map(e->e.packet().sequence()).toList());var r=Phase7Timing.reconstruct(t,exactConfig());assertTrue(r.frames().get(2).timing().windows().stream().anyMatch(w->w.kind()==WindowKind.REORDERING));}
  @Test void serverTickGapIsExplicit(){var r=Phase7Timing.reconstruct(timeline(new RawPacket(1,0,new Move(Vec3.ZERO,0f,0f,true,0L)),new RawPacket(2,200_000_000L,new Move(new Vec3(.2,0,0),0f,0f,true,4L))),exactConfig());assertTrue(r.frames().get(1).timing().windows().stream().anyMatch(w->w.kind()==WindowKind.SERVER_TICK_GAP));}
  @Test void explicitClientTickContradictionIsIdentifiedAsInconsistentTiming(){var r=Phase7Timing.reconstruct(timeline(new RawPacket(1,0,new Move(Vec3.ZERO,0f,0f,true,0L)),new RawPacket(2,50_000_000L,new Move(new Vec3(.1,0,0),0f,0f,true,10L))),exactConfig());assertEquals(Consistency.INCONSISTENT,r.consistency());}
  @Test void impossibleTimingIsExplainableAndNotAPlayerViolation(){var r=Phase7Timing.reconstruct(timeline(new RawPacket(1,0,new Move(Vec3.ZERO,0f,0f,true,0L)),new RawPacket(2,50_000_000L,new Move(new Vec3(.1,0,0),0f,0f,true,10L))),exactConfig());assertEquals(Consistency.INCONSISTENT,r.consistency());assertTrue(r.consistencyReasons().getFirst().contains("outside timing bounds"));}
  @Test void worldTimingIsNotAssumedExactWhenNetworkTimingIsVariable(){Config c=new Config(50_000_000L,50_000_000L,50_000_000L,new LatencyBounds(0,25_000_000L),new LatencyBounds(0,25_000_000L),new TickDelayBounds(0,0),new TickDelayBounds(0,0),250_000_000L,3,128);var r=Phase7Timing.reconstruct(timeline(new RawPacket(1,0,new Move(Vec3.ZERO,0f,0f,true,0L)),new RawPacket(2,50_000_000L,new ChunkData(new World.Chunk(0,0),Map.of()))),c);assertFalse(Phase7Timing.worldTimingExhaustive(r,2));assertTrue(r.timingFor(2).orElseThrow().windows().stream().anyMatch(w->w.kind()==WindowKind.WORLD_UPDATE));}
  @Test void duplicatePacketCannotTriggerSecondTeleportSynchronizationEvent(){var t=timeline(new RawPacket(1,0,new Move(Vec3.ZERO,0f,0f,true,0L)),new RawPacket(7,50_000_000L,new Teleport(7,Vec3.ZERO,0f,0f)),new RawPacket(7,51_000_000L,new Teleport(7,Vec3.ZERO,0f,0f)));var r=Phase7Timing.reconstruct(t,exactConfig());assertEquals(1,r.frames().get(1).after().synchronizationEpoch());assertEquals(1,r.frames().get(2).after().synchronizationEpoch());assertEquals(SyncStatus.RECOVERING,r.frames().get(2).after().status());assertEquals(1,r.frames().get(2).timing().windows().stream().filter(w->w.kind()==WindowKind.TELEPORT).count());assertEquals(1,r.frames().get(2).timing().windows().stream().filter(w->w.kind()==WindowKind.DUPLICATE).count());}
  @Test void duplicatePacketCannotAdvanceLogicalPlayerStateTwiceDuringReplay(){var t=timeline(new RawPacket(1,0,new Move(new Vec3(1,0,0),0f,0f,true,0L)),new RawPacket(1,1,new Move(new Vec3(2,0,0),0f,0f,true,0L)));var replay=Replay.replay(State.Player.initial(Vec3.ZERO),t);assertEquals(new Vec3(1,0,0),replay.frames().get(0).after().position());assertEquals(new Vec3(1,0,0),replay.frames().get(1).after().position());assertTrue(replay.frames().get(1).after().uncertain());}
  @Test void serverToClientEventBeforeClientAnchorRemainsUnknown(){var r=Phase7Timing.reconstruct(timeline(new RawPacket(1,0,new Velocity(new Vec3(.1,0,0)))),exactConfig());assertEquals(TimingSource.SERVER_CAPTURE_ONLY,r.frames().getFirst().timing().source());assertTrue(r.frames().getFirst().timing().uncertain());}
  @Test void replayArtifactReproducesTimingExactly(){var t=timeline(new RawPacket(1,0,new Move(Vec3.ZERO,0f,0f,true,0L)),new RawPacket(2,75_000_000L,new Velocity(new Vec3(.3,.2,0))));var config=new Config(50_000_000L,50_000_000L,50_000_000L,new LatencyBounds(0,25_000_000L),new LatencyBounds(0,25_000_000L),new TickDelayBounds(0,1),new TickDelayBounds(0,1),250_000_000L,3,128);var artifact=Phase7Replay.of(t,config);var decoded=Phase7Replay.decode(artifact.encode());assertEquals(artifact,decoded);assertEquals(artifact.reconstruct().canonicalText(),decoded.reconstruct().canonicalText());assertArrayEquals(artifact.encode(),decoded.encode());}
  @Test void canonicalReplayTextIsStableAcrossRepeatedReconstruction(){var t=timeline(new RawPacket(1,0,new Move(Vec3.ZERO,0f,0f,true,0L)),new RawPacket(2,50_000_000L,new Move(new Vec3(.1,0,0),0f,0f,true,null)));assertEquals(Phase7Timing.reconstruct(t,exactConfig()).canonicalText(),Phase7Timing.reconstruct(t,exactConfig()).canonicalText());}
  @Test void defaultTimingAssumptionsAreExplicitAndConfigurable(){Config c=Config.defaultConfig();assertEquals(50_000_000L,c.serverTickNanos());assertEquals(100_000_000L,c.upstreamLatency().maxNanos());assertEquals(100_000_000L,c.downstreamLatency().maxNanos());assertEquals(3,c.recoveryStableEvents());assertEquals(128,c.maxTimingCandidates());}
}
