package dev.phantom.ac;

import java.io.Serializable;
import java.util.*;
import static dev.phantom.ac.Maths.*;
import static dev.phantom.ac.State.*;

/** Strict, lossless-enough interchange contract for independently captured Java 1.21.11 traces. */
public final class Phase5TraceTool {
  private Phase5TraceTool() {}
  public static final String MAGIC="# phantom-phase5-trace version=1 protocol=minecraft-java-1.21.11 format=tsv";
  public static final String HEADER="tick\tclient_tick\treceive_nanos\tx\ty\tz\tvx\tvy\tvz\tyaw\tpitch\ton_ground\tforward\tstrafe\tjump\tsprint\tsneak\tpose\tgamemode\tfluid\tsubmerged\tclimbable\tgliding\tbase_movement_speed\tmodifiers\tspeed_amp\tslowness_amp\tjump_boost_amp\tlevitation\tslow_falling\tknockback_x\tknockback_y\tknockback_z\tvelocity_packet\tcorrection_id\tcorrection_pending\tworld_identity\tworld_tick\tcollision\tstep_attempted\tstep_succeeded\tcollision_x\tcollision_y\tcollision_z\tinput_source\tclient_version";
  public static final int COLUMN_COUNT=46;

  public record Row(long tick,long clientTick,long receiveNanos,double x,double y,double z,double vx,double vy,double vz,float yaw,float pitch,
                    boolean onGround,int forward,int strafe,boolean jump,boolean sprint,boolean sneak,Phase5Mechanics.Pose pose,String gamemode,
                    Phase5Mechanics.Fluid fluid,boolean submerged,boolean climbable,boolean gliding,double baseMovementSpeed,List<Phase5Mechanics.AttributeModifier> modifiers,
                    Phase5Mechanics.MovementEffects effects,Phase5Mechanics.Vec3Like knockback,boolean velocityPacket,long correctionId,boolean correctionPending,
                    String worldIdentity,long worldTick,boolean collision,boolean stepAttempted,boolean stepSucceeded,boolean collisionX,boolean collisionY,boolean collisionZ,
                    String inputSource,String clientVersion) implements Serializable {
    public Row { modifiers=List.copyOf(modifiers);Objects.requireNonNull(pose);Objects.requireNonNull(gamemode);Objects.requireNonNull(fluid);Objects.requireNonNull(effects);Objects.requireNonNull(knockback);Objects.requireNonNull(worldIdentity);Objects.requireNonNull(inputSource);Objects.requireNonNull(clientVersion); }
  }
  public record ReferenceTrace(String sourceId,String capturedAtUtc,String clientVersion,List<Row> rows) implements Serializable {
    public ReferenceTrace { if(sourceId==null||sourceId.isBlank())throw new IllegalArgumentException("sourceId is required");if(capturedAtUtc==null||capturedAtUtc.isBlank())throw new IllegalArgumentException("capturedAtUtc is required");rows=List.copyOf(rows); }
  }
  public record Diagnostic(long tick,String field,String expected,String actual,double delta,String message) implements Serializable {}
  public record ValidationResult(boolean valid,List<Diagnostic> diagnostics) implements Serializable {public ValidationResult{diagnostics=List.copyOf(diagnostics);}}

  public static List<String> write(ReferenceTrace trace) {
    List<String> out=new ArrayList<>();out.add(MAGIC);out.add("# source_id="+escape(trace.sourceId()));out.add("# captured_at_utc="+escape(trace.capturedAtUtc()));out.add(HEADER);
    for(Row r:trace.rows()) out.add(String.join("\t",Long.toString(r.tick()),Long.toString(r.clientTick()),Long.toString(r.receiveNanos()),d(r.x()),d(r.y()),d(r.z()),d(r.vx()),d(r.vy()),d(r.vz()),d(r.yaw()),d(r.pitch()),b(r.onGround()),Integer.toString(r.forward()),Integer.toString(r.strafe()),b(r.jump()),b(r.sprint()),b(r.sneak()),r.pose().name(),r.gamemode(),r.fluid().name(),b(r.submerged()),b(r.climbable()),b(r.gliding()),d(r.baseMovementSpeed()),modifiers(r.modifiers()),Integer.toString(r.effects().speedAmplifier()),Integer.toString(r.effects().slownessAmplifier()),Integer.toString(r.effects().jumpBoostAmplifier()),b(r.effects().levitation()),b(r.effects().slowFalling()),d(r.knockback().x()),d(r.knockback().y()),d(r.knockback().z()),b(r.velocityPacket()),Long.toString(r.correctionId()),b(r.correctionPending()),escape(r.worldIdentity()),Long.toString(r.worldTick()),b(r.collision()),b(r.stepAttempted()),b(r.stepSucceeded()),b(r.collisionX()),b(r.collisionY()),b(r.collisionZ()),escape(r.inputSource()),escape(r.clientVersion())));
    return List.copyOf(out);
  }

  public static ReferenceTrace read(List<String> lines) {
    if(lines.size()<4||!MAGIC.equals(lines.getFirst())||!HEADER.equals(lines.get(3)))throw new IllegalArgumentException("invalid Phase 5 trace header");
    String source=meta(lines.get(1),"source_id");String captured=meta(lines.get(2),"captured_at_utc");List<Row> rows=new ArrayList<>();long previousTick=-1;long previousClient=-1;
    for(int i=4;i<lines.size();i++){String line=lines.get(i);if(line.isBlank()||line.startsWith("#"))continue;String[] c=line.split("\\t",-1);if(c.length!=COLUMN_COUNT)throw new IllegalArgumentException(invalid(i,"expected "+COLUMN_COUNT+" columns, got "+c.length));try{Row r=parse(c);if(r.tick()<=previousTick)throw new IllegalArgumentException(invalid(i,"server/simulation ticks must strictly increase"));if(r.clientTick()<previousClient)throw new IllegalArgumentException(invalid(i,"client ticks must not decrease"));if(r.receiveNanos()<0)throw new IllegalArgumentException(invalid(i,"receive_nanos must be non-negative"));validateFinite(r,i);previousTick=r.tick();previousClient=r.clientTick();rows.add(r);}catch(IllegalArgumentException e){if(e.getMessage()!=null&&e.getMessage().startsWith("invalid trace row"))throw e;throw new IllegalArgumentException(invalid(i,e.getMessage()==null?"invalid field":e.getMessage()),e);}}
    return new ReferenceTrace(source,captured,rows.isEmpty()?"minecraft-java-1.21.11":rows.getFirst().clientVersion(),rows);
  }

  public static ValidationResult validate(ReferenceTrace trace) {
    List<Diagnostic> d=new ArrayList<>();long last=-1,lastClient=-1,lastReceive=-1;for(Row r:trace.rows()){if(r.tick()<=last)d.add(new Diagnostic(r.tick(),"tick",">"+last,Long.toString(r.tick()),0,"ticks must strictly increase"));if(r.clientTick()<lastClient)d.add(new Diagnostic(r.tick(),"client_tick",">="+lastClient,Long.toString(r.clientTick()),0,"client tick regressed"));if(r.receiveNanos()<lastReceive)d.add(new Diagnostic(r.tick(),"receive_nanos",">="+lastReceive,Long.toString(r.receiveNanos()),0,"receive time regressed"));last=r.tick();lastClient=r.clientTick();lastReceive=r.receiveNanos();if(r.clientVersion().isBlank())d.add(new Diagnostic(r.tick(),"client_version","non-empty",r.clientVersion(),0,"client version is required"));if(r.worldIdentity().isBlank())d.add(new Diagnostic(r.tick(),"world_identity","non-empty",r.worldIdentity(),0,"world identity is required"));}return new ValidationResult(d.isEmpty(),d);
  }

  public static List<Diagnostic> firstDivergence(ReferenceTrace expected, Simulation.Trace actual, double epsilon) {
    List<Diagnostic> d=new ArrayList<>();int n=Math.min(expected.rows().size(),actual.frames().size());for(int i=0;i<n;i++){Row e=expected.rows().get(i);Simulation.Frame a=actual.frames().get(i);if(e.tick()!=a.tick()){d.add(new Diagnostic(e.tick(),"tick",Long.toString(e.tick()),Long.toString(a.tick()),a.tick()-e.tick(),"first tick identity mismatch"));return List.copyOf(d);}Player p=a.state();check(d,e.tick(),"x",e.x(),p.position().x(),epsilon);check(d,e.tick(),"y",e.y(),p.position().y(),epsilon);check(d,e.tick(),"z",e.z(),p.position().z(),epsilon);check(d,e.tick(),"vx",e.vx(),p.velocity().x(),epsilon);check(d,e.tick(),"vy",e.vy(),p.velocity().y(),epsilon);check(d,e.tick(),"vz",e.vz(),p.velocity().z(),epsilon);check(d,e.tick(),"yaw",e.yaw(),p.yaw(),epsilon);check(d,e.tick(),"pitch",e.pitch(),p.pitch(),epsilon);if(e.onGround()!=p.onGround())d.add(new Diagnostic(e.tick(),"on_ground",b(e.onGround()),b(p.onGround()),1,"ground-state mismatch"));if(e.forward()!=a.input().forward()||e.strafe()!=a.input().strafe()||e.jump()!=a.input().jump())d.add(new Diagnostic(e.tick(),"input","reference input",a.input().toString(),0,"input mismatch"));if(!d.isEmpty())return List.copyOf(d);}if(expected.rows().size()!=actual.frames().size())d.add(new Diagnostic(n,"trace_length",Integer.toString(expected.rows().size()),Integer.toString(actual.frames().size()),actual.frames().size()-expected.frames().size(),"trace length mismatch"));return List.copyOf(d);
  }
  private static void check(List<Diagnostic>d,long tick,String f,double e,double a,double eps){double delta=a-e;if(!Double.isFinite(a)||Math.abs(delta)>eps)d.add(new Diagnostic(tick,f,Double.toString(e),Double.toString(a),delta,"numeric divergence"));}
  private static Row parse(String[] c){return new Row(Long.parseLong(c[0]),Long.parseLong(c[1]),Long.parseLong(c[2]),Double.parseDouble(c[3]),Double.parseDouble(c[4]),Double.parseDouble(c[5]),Double.parseDouble(c[6]),Double.parseDouble(c[7]),Double.parseDouble(c[8]),Float.parseFloat(c[9]),Float.parseFloat(c[10]),Boolean.parseBoolean(c[11]),Integer.parseInt(c[12]),Integer.parseInt(c[13]),Boolean.parseBoolean(c[14]),Boolean.parseBoolean(c[15]),Boolean.parseBoolean(c[16]),Phase5Mechanics.Pose.valueOf(c[17]),c[18],Phase5Mechanics.Fluid.valueOf(c[19]),Boolean.parseBoolean(c[20]),Boolean.parseBoolean(c[21]),Boolean.parseBoolean(c[22]),Double.parseDouble(c[23]),parseModifiers(c[24]),new Phase5Mechanics.MovementEffects(Integer.parseInt(c[25]),Integer.parseInt(c[26]),Integer.parseInt(c[27]),Boolean.parseBoolean(c[28]),Boolean.parseBoolean(c[29])),new Phase5Mechanics.Vec3Like(Double.parseDouble(c[30]),Double.parseDouble(c[31]),Double.parseDouble(c[32])),Boolean.parseBoolean(c[33]),Long.parseLong(c[34]),Boolean.parseBoolean(c[35]),unescape(c[36]),Long.parseLong(c[37]),Boolean.parseBoolean(c[38]),Boolean.parseBoolean(c[39]),Boolean.parseBoolean(c[40]),Boolean.parseBoolean(c[41]),Boolean.parseBoolean(c[42]),Boolean.parseBoolean(c[43]),unescape(c[44]),unescape(c[45]));}
  private static List<Phase5Mechanics.AttributeModifier> parseModifiers(String s){if(s==null||s.isBlank()||s.equals("-"))return List.of();List<Phase5Mechanics.AttributeModifier> out=new ArrayList<>();for(String m:s.split(";",-1)){if(m.isBlank())continue;String[] p=m.split(":",3);if(p.length!=3)throw new IllegalArgumentException("invalid modifier "+m);out.add(new Phase5Mechanics.AttributeModifier(unescape(p[0]),Double.parseDouble(p[1]),Phase5Mechanics.ModifierOperation.valueOf(p[2])));}return out;}
  private static String modifiers(List<Phase5Mechanics.AttributeModifier> ms){if(ms.isEmpty())return "-";return ms.stream().map(m->escape(m.id())+":"+Double.toString(m.amount())+":"+m.operation().name()).reduce((a,b)->a+";"+b).orElse("-");}
  private static void validateFinite(Row r,int row){double[] v={r.x(),r.y(),r.z(),r.vx(),r.vy(),r.vz(),r.yaw(),r.pitch(),r.baseMovementSpeed()};for(double x:v)if(!Double.isFinite(x))throw new IllegalArgumentException(invalid(row,"non-finite numeric value"));}
  private static String meta(String line,String key){String p="# "+key+"=";if(!line.startsWith(p))throw new IllegalArgumentException("invalid metadata "+key);return unescape(line.substring(p.length()));}
  private static String d(double x){return Double.toString(x);} private static String b(boolean x){return Boolean.toString(x);} private static String escape(String s){return s.replace("%","%25").replace("\t","%09").replace("\n","%0A").replace("\r","%0D");} private static String unescape(String s){return s.replace("%0D","\r").replace("%0A","\n").replace("%09","\t").replace("%25","%");} private static String invalid(int row,String why){return "invalid trace row "+(row+1)+": "+why;}
}
