    if (selected != null) {
      options.add(selected.constraint());

      /*
       * A ClientInput whose Phase 7 input timing can land on more than one tick
       * is a transition boundary, not a single historical fact. Keep the state
       * immediately before that transition as a second alternative at the
       * boundary. This is linear and lets the existing Phase 6 candidate frontier
       * carry the ambiguity instead of building every input chronology up front.
       */
      if (ambiguousInputTimingAt(selected.sequence(), simulationTick, movementSequence)) {
        options.add(inputBeforeSequence(
            history, simulationTick, selected.sequence(), movementSequence));
      }
    }

    for (UncertainInput input : uncertainInputs) {
      if (input.sequence() > movementSequence || simulationTick < input.earliestClientTick()) {
        continue;
      }
      TimedInput latest = latestTimedInput(history, simulationTick, movementSequence);
      if (latest == null || input.sequence() > latest.sequence()) {
        options.add(InputConstraint.any());
      }
    }

    /*
     * Match Grim at the live movement boundary: the newest ClientInput already
     * received before this movement is a valid held-state alternative for the
     * final simulated tick. Do not apply this live overlay to earlier catch-up
     * ticks, where it could become retroactive input.
     */
    if (shouldOverlayCurrentInput(
        simulationTick,
        targetTick,
        currentInputSequence,
        movementSequence,
        currentInputPossibleSimulationTicks,
        movementTimingUncertain)) {
      options.add(currentInput);

      /*
       * An unresolved movement boundary can put the newest held input packet
       * on either side of the client's tick-end. Keep the immediately preceding
       * held state as a sibling hypothesis so the newest packet is not applied
       * retroactively to movement that was already generated by the client.
       */
      if (movementTimingUncertain) {
        InputConstraint previous = inputBeforeSequence(
            history, simulationTick, currentInputSequence, movementSequence);
        if (!previous.equals(currentInput)) {
          options.add(previous);
        }
      }
    }

    if (options.isEmpty()) return List.of(neutralInput);
    return List.copyOf(options);
  }

  static boolean shouldOverlayCurrentInput(
      long simulationTick,
      long targetTick,
      long currentInputSequence,
      long movementSequence,
      List<Long> possibleSimulationTicks) {
    return shouldOverlayCurrentInput(
        simulationTick,
        targetTick,
        currentInputSequence,
        movementSequence,
        possibleSimulationTicks,
        false);
  }

  static boolean shouldOverlayCurrentInput(
      long simulationTick,
      long targetTick,
      long currentInputSequence,
      long movementSequence,